mongo:
  image: mongo:3.4.5
neo:
  image: neo4j:3.2
  environment:
     - NEO4J_AUTH=none
mysql:
   image: mysql:5.7.18
   environment:
      - MYSQL_ROOT_PASSWORD=root
tester:
  build: .
  dockerfile: Dockerfile-tester
  links:
    - mongo
    - neo
    - mysql
